### ISSUE TITLE
Project Alpha

### ISSUE THREAD

**Issue by rovertdude** [Develop-Team/DevelopFreedomMod#12]
Project Alpha is going to be Version 2.0 of the DevelopFreedomMod.
Manager:
rovertdude

Moderator:
adroition

Moderator has effectively manager permissions however cannot merge the final pull request and can't freeze
I will be making the fork and Pull Request.

This has been waived by PuggyCrew to be no longer frozen. Approved by rovertdude.
Minimal PR's to merge: 5

**Comment by adroition** [comment]
Project has been finished!
