### ISSUE TITLE
/toggle crashes the server

### ISSUE THREAD

**Issue by PuggyCrew** [Develop-Team/DevelopFreedomMod#24]
So, I haven't been able to reproduce this glitch. There's some way to crash a server using /toggle. I'm requesting a bounty. Any user can do it that aren't effected by a command block.

**Comment by rovertdude** [comment]
Added as a large bounty. I want a way to reproduce this.

**Comment by rovertdude** [comment]
Claimed in #25, still needing a fix

**Comment by rovertdude** [comment]
Bounty recreated in need of a fix

**Comment by rovertdude** [comment]
Fixed in #26
