### ISSUE TITLE
Bounty Claim

### ISSUE THREAD

**Issue by PuggyCrew** [Develop-Team/DevelopFreedomMod#25]
This is claiming #24 as I found the repro method
Steps to Reproduce:
  - On a server, do /toggle aaEJFerugh31
Reason this Crashes: This is the exact variable needed to overflow the plugin.

**Comment by rovertdude** [comment]
Attempting to repro

**Comment by rovertdude** [comment]
Can reproduce, claimed!
#23

**Comment by rovertdude** [comment]
Fixed in #26
