### ISSUE TITLE
/cbtool can use blocked WorldEdit commands

### ISSUE THREAD

**Issue by rovertdude** [Develop-Team/DevelopFreedomMod#27]
The command /cbtool is allowed to use some blocked WorldEdit commands

**Comment by PuggyCrew** [comment]
Examples?

**Comment by adroition** [comment]
Can reproduce

**Comment by PuggyCrew** [comment]
when adro self assigns you know it's gonna get fixed

**Comment by PuggyCrew** [comment]
fixed in #28
