### ISSUE TITLE
Project B. Project A and A(b) have been closed.

### ISSUE THREAD

**Issue by PuggyCrew** [Develop-Team/DevelopFreedomMod#9]
This is announcing the arrival of Project B.
This will be deemed as either 2.0 or 1.2 (1.1 was a(B)) depending on pull requests.
Hell, we could make it 1.1.1 if we have too little.
Project A and A(B) are now closed.
As of 10/13/16, Project B is opened.
Milestone list:
Project A (1.0)
Project A(B) (1.1)
Project B (Unconfirmed)

The managers of this milestone and project will be:
@adroition 
@PuggyCrew

**Comment by rovertdude** [comment]
both added to @Develop-Team/current-project-managers-tfm

**Comment by adroition** [comment]
Project frozen by @PuggyCrew due to the project being finished.
Awaiting @rovertdude approval on #10

**Comment by adroition** [comment]
Goodbye, Project B.
You were where I was really involved.
